name: Build, Push, and Deploy
on:
  push:
    branches: [ rick-test ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-gcloud-auth-plugin,kubectl'  # Install the plugin

      - name: Set up Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-web3/hello-web3:latest" .
          docker push "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-web3/hello-web3:latest"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --region us-central1 \
          --project ${{ secrets.GCP_PROJECT_ID }}
  
      - name: Create API Key Secret
        run: |
          kubectl create secret generic polygon-api-key \
          --from-literal=POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }} \
          --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy with Helm
        run: |
          helm upgrade --install helloweb3 ./helm/helloWeb3 \
          --namespace helloweb3 \
          --set image.tag=$GITHUB_SHA \
          --set secret.secretKeyRefName=polygon-api-key \
          --set service.type=LoadBalancer \
          --set ingress.hosts[0].host=${{ secrets.DOMAIN_NAME }} \
          --set ingress.hosts[1].host=app.${{ secrets.DOMAIN_NAME }} \
          --set ingress.tls[0].hosts[0]=${{ secrets.DOMAIN_NAME }} \
          --atomic \
          --timeout 5m0s