name: Build, Push, and Deploy
on:
  push:
    branches: [ rick-test ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-web3/hello-web3:latest" .
          docker push "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-web3/hello-web3:latest"

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --region us-central1 \
          --project ${{ secrets.GCP_PROJECT }}
  
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/hello-web3 hello-web3=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/hello-web3/hello-web3:latest