name: Build, Push, and Deploy
on:
  push:
    branches: [ rick-test ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-web3" .
          docker push "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-web3"

      - name: Deploy to GKE
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: hello-web3
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-web3:main-${{ steps.sha.outputs.short_sha }}
          cluster_name: blockchain-cluster
          location: us-central1
          credentials: ${{ secrets.GCP_SA_KEY }}